# Configuration for HMS Harmful Brain Activity Classification System

# Dataset Configuration
dataset:
  name: "hms-harmful-brain-activity-classification"
  kaggle_competition: "hms-harmful-brain-activity-classification"
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"
  download_batch_size: 100  # Download files in batches
  eeg_sampling_rate: 200  # Hz
  eeg_duration: 50  # seconds
  spectrogram_duration: 600  # seconds (10 minutes)
  num_classes: 6
  val_split: 0.2  # Validation split ratio
  test_split: 0.1  # Test split ratio (if applicable)
  seed: 42  # Random seed for reproducibility
  
# EEG Channel Configuration
eeg:
  channels:
    - "Fp1"
    - "Fp2"
    - "F3"
    - "F4"
    - "C3"
    - "C4"
    - "P3"
    - "P4"
    - "O1"
    - "O2"
    - "F7"
    - "F8"
    - "T3"
    - "T4"
    - "T5"
    - "T6"
    - "Fz"
    - "Cz"
    - "Pz"
  reference_channels: ["A1", "A2"]
  montage: "standard_1020"  # EEG montage system
  bad_channel_detection:
    enabled: true
    threshold_std: 5.0  # Standard deviation threshold
    correlation_threshold: 0.1  # Minimum correlation with other channels
  
# Preprocessing Configuration
preprocessing:
  # General settings
  num_channels: 19
  window_length: 50  # seconds
  overlap: 0.5  # Window overlap ratio
  
  # Filtering
  filter:
    lowcut: 0.5  # Hz
    highcut: 50.0  # Hz
    filter_order: 4
    filter_type: "butterworth"
    notch_freq: 60.0  # Hz (power line frequency)
    notch_quality: 30  # Notch filter quality factor
  
  # Artifact Removal
  artifact_removal:
    use_ica: true
    n_components: 20
    ica_method: "fastica"
    eog_channels: ["Fp1", "Fp2"]
    muscle_threshold: 3.0  # Z-score threshold
    eye_blink_threshold: 4.0  # Z-score threshold
    
  # Denoising
  denoising:
    use_wavelet: true
    wavelet_type: "db4"
    wavelet_level: 5
    denoise_method: "soft"  # soft or hard thresholding
    
  # Normalization
  normalization:
    method: "robust"  # Options: "standard", "minmax", "robust"
    clip_percentile: 99.5  # Clip extreme values
    
  # Spectrogram Generation
  spectrogram:
    window_size: 256
    overlap: 128
    nfft: 512
    freq_min: 0.5
    freq_max: 50.0
    colormap: "viridis"
    log_scale: true
    
# Model Configuration
models:
  # ResNet1D-GRU for raw EEG
  resnet1d_gru:
    enabled: true
    # ResNet1D parameters
    resnet:
      initial_filters: 64
      num_blocks: [2, 2, 2, 2]
      kernel_size: 7
      dropout: 0.3
      activation: "relu"
      batch_norm: true
      use_se: true
      use_multiscale: true
      
    # GRU parameters
    gru:
      hidden_size: 256
      num_layers: 2
      bidirectional: true
      dropout: 0.3
      n_heads: 8
      
    # Attention mechanism
    attention:
      enabled: true
      num_heads: 8
      dropout: 0.1
      
    # Training parameters
    training:
      batch_size: 32
      learning_rate: 0.001
      weight_decay: 0.0001
      epochs: 100
      early_stopping_patience: 15
      lr_scheduler: "cosine"  # cosine, step, exponential
      warmup_epochs: 5
      
  # EfficientNet for spectrograms
  efficientnet:
    enabled: true
    model_name: "efficientnet-b3"
    pretrained: true
    num_classes: 6
    dropout: 0.3
    freeze_backbone: false
    unfreeze_at_epoch: 10
    training:
      batch_size: 16
      learning_rate: 0.0001
      weight_decay: 0.00001
      epochs: 80
      early_stopping_patience: 12
      mixup_alpha: 0.2  # Mixup augmentation
      cutmix_alpha: 1.0  # Cutmix augmentation
      
  # Ensemble Configuration
  ensemble:
    enabled: true
    method: "stacking"  # Options: "voting", "averaging", "stacking"
    meta_learner: "xgboost"
    meta_learner_params:
      n_estimators: 100
      max_depth: 6
      learning_rate: 0.1
      subsample: 0.8
      colsample_bytree: 0.8
    confidence_weighting: true
    uncertainty_estimation: true
      
# Training Configuration
training:
  # General settings
  device: "cuda"  # cuda or cpu
  num_workers: 4  # Data loading workers
  pin_memory: true
  checkpoint_dir: "models/checkpoints"
  
  # Cross-validation
  cross_validation:
    n_folds: 5
    strategy: "patient_grouped"  # Ensure patient independence
    shuffle: true
    
  # Class balancing
  class_balancing:
    strategy: "weighted"  # Options: "weighted", "oversampling", "undersampling", "smote"
    class_weights: "balanced"  # balanced or custom weights
    
  # Data augmentation
  augmentation:
    time_domain:
      jitter: 0.1
      scaling: 0.2
      time_shift: 0.1
      gaussian_noise: 0.05
      
    frequency_domain:
      freq_mask: 0.1
      time_mask: 0.1
      spec_augment: true
      
  # Optimization
  optimization:
    method: "optuna"
    n_trials: 50
    timeout: 86400  # 24 hours
    pruner: "median"  # Optuna pruner
    sampler: "tpe"  # Optuna sampler
    
  # Mixed precision training
  mixed_precision:
    enabled: true
    opt_level: "O1"  # O0, O1, O2, O3
    
# Class Labels
classes:
  - "Seizure"
  - "LPD"  # Lateralized Periodic Discharges
  - "GPD"  # Generalized Periodic Discharges
  - "LRDA"  # Lateralized Rhythmic Delta Activity
  - "GRDA"  # Generalized Rhythmic Delta Activity
  - "Other"
  
# Evaluation Configuration
evaluation:
  metrics:
    - "accuracy"
    - "sensitivity"
    - "specificity"
    - "f1_score"
    - "auc_roc"
    - "confusion_matrix"
    - "cohen_kappa"
    - "matthews_corrcoef"
    
  clinical_metrics:
    - "seizure_detection_sensitivity"
    - "false_alarm_rate"
    - "detection_latency"
    - "positive_predictive_value"
    - "negative_predictive_value"
    
  bootstrap:
    enabled: true
    n_bootstrap: 1000
    confidence_level: 0.95
    
# Interpretability Configuration
interpretability:
  methods:
    - "gradcam"
    - "integrated_gradients"
    - "shap"
    - "lime"
    - "attention_weights"
    
  uncertainty:
    method: "monte_carlo_dropout"
    n_samples: 100
    temperature_scaling: true
    
  feature_importance:
    enabled: true
    permutation_repeats: 10
    
# Deployment Configuration
deployment:
  api:
    host: "0.0.0.0"
    port: 8000
    workers: 4
    reload: false
    cors_origins: ["*"]
    
  model_serving:
    batch_size: 1
    max_batch_size: 32
    timeout: 30  # seconds
    cache_predictions: true
    cache_size: 1000
    
  monitoring:
    log_predictions: true
    drift_detection: true
    performance_tracking: true
    alert_thresholds:
      latency_ms: 1000
      error_rate: 0.01
      memory_usage_percent: 80
    
# Performance Optimization
optimization:
  model_compression:
    pruning_sparsity: 0.3
    quantization: "int8"
    knowledge_distillation: true
    
  inference:
    use_gpu: true
    mixed_precision: true
    onnx_export: true
    tensorrt_optimization: true
    batch_inference: true
    
# Logging Configuration
logging:
  level: "INFO"
  mlflow_tracking_uri: "http://localhost:5000"
  wandb_project: "hms-brain-activity"
  tensorboard_dir: "logs/tensorboard"
  experiment_name: "hms-eeg-classification"
  run_name_prefix: "run"
  log_model_architecture: true
  log_gradients: false
  log_activations: false
  log_every_n_steps: 10
  
# Data Management
data_management:
  cache_processed_data: true
  cache_dir: "data/processed/cache"
  data_version: "v1.0"
  validate_data: true
  remove_corrupted: true
  backup_frequency: "daily"
  
# System Configuration
system:
  random_seed: 42
  deterministic: true
  benchmark: false
  max_memory_gb: 30
  gpu_memory_fraction: 0.9
  distributed_training: false 