# Production config - tested locally first
dataset:
  name: "hms-harmful-brain-activity-classification"
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"
  eeg_sampling_rate: 200
  eeg_duration: 50
  num_classes: 6
  val_split: 0.15
  seed: 42
  max_samples: 15000  # Fast version - 15k samples instead of 106k
  
preprocessing:
  num_channels: 19
  window_length: 50
  overlap: 0.25  # Reduced for speed
  
  filter:
    lowcut: 0.5
    highcut: 50.0
    filter_order: 4
    notch_freq: 60.0
    
models:
  resnet1d_gru:
    enabled: true
    resnet:
      initial_filters: 32  # Tested locally
      num_blocks: [2, 2, 2]  # Tested locally
      kernel_size: 5
      dropout: 0.3
    gru:
      hidden_size: 128  # Tested locally
      num_layers: 1
      bidirectional: true
      dropout: 0.3
    training:
      batch_size: 64  # For H100
      learning_rate: 0.003  # Faster convergence
      epochs: 15  # Reduced for speed
      early_stopping_patience: 5
      
  efficientnet:
    enabled: true
    model_name: "efficientnet-b0"  # Tested locally
    pretrained: true
    training:
      batch_size: 32  # For H100
      learning_rate: 0.001
      epochs: 12  # Reduced for speed
      
  ensemble:
    enabled: false  # Skip for speed
    
training:
  device: "cuda"
  num_workers: 4
  mixed_precision:
    enabled: true
    opt_level: "O2"  # Aggressive optimization
    
optimization:
  onnx_export: true
  onnx_opset_version: 17
  optimize_for_inference: true
  dynamic_axes: true